version: 2.1

parameters:
  docker_image:
    type: string
    default: python:3.10.0-bullseye 

jobs:
  linting:
    docker:
      - image: << pipeline.parameters.docker_image >>
    
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pylint --disable=E0602,C0116,C0103    kazi.py
           
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

  coverage:
    docker:
        - image: << pipeline.parameters.docker_image >>
    steps:
      - checkout
      - run:
          name: run job
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python3 kazi.py
      

      
workflows:
  version: 2
  commit:
    jobs:
      - linting
      
  nightly:
    triggers: #use the triggers key to indicate a scheduled build
      - schedule:
          cron: "0 8 * * *" # use cron syntax to set the schedule
          filters:
            branches:
              only: main
          
    jobs:
      - coverage